### ISSUE TITLE
feat. request - Populate chat with text

### ISSUE THREAD

**Issue by triphora** [UltraBlackLinux/MineMenuFabric#10]
It would be useful to have something populate the chat box with a message but not actually send it.

As an example of use case, on the multiplayer server I play on, it's customary to welcome new players who join, so I'd like the ability to autofill the chat box with `Welcome to <server>,` then type in the player's name myself.

**Comment by UltraBlackLinux** [comment]
@wafflecoffee 
I can try to do that, it's a bit of a pain, as I need to figure out, how minecraft does it xD
Thanks for your suggestion!

**Comment by UltraBlackLinux** [comment]
Wasn't that bad after all lol

**Comment by triphora** [comment]
cool, thanks! :D
