### ISSUE TITLE
UI is working when I press the "R" but it printing nothing in chat. 

### ISSUE THREAD

**Issue by HappyClownn** [UltraBlackLinux/MineMenuFabric#11]
It is just a copy-paste from CurseForge website.

My problem did not fix with the new update. So I decided to move the problem/subject here.

"I just installed your mod. The GUI is working but it doesn't prints anything in chat somehow. I'm currently trying to add /home command to mods hud menu. Can you help?"

![image](https://user-images.githubusercontent.com/69100788/117575565-13beb300-b0eb-11eb-8ddf-3f17a945ba50.png)

**Installed mods:**

![image](https://user-images.githubusercontent.com/69100788/117575505-cb06fa00-b0ea-11eb-889f-0873c5a2bab9.png)
![image](https://user-images.githubusercontent.com/69100788/117575508-cfcbae00-b0ea-11eb-9bfa-7b3d99708fdc.png)

**Comment by UltraBlackLinux** [comment]
First of all: Is that top screenshot old or something? It doesn't make sense to me, that the translation file seems to be messed up for you
Could you try just saying something in chat, without the "/" - does that also not work?

**Comment by HappyClownn** [comment]
Yeah unfortunately. I tried it without a slash. It didn't print anything :/

Is there any way to fix the translation file? I don't get any problems in other mods. I hope I can fix this.

**Comment by UltraBlackLinux** [comment]
@Ozaxx 
Could you try the latest version, and if that doesn't work, send me your config file?

**Comment by HappyClownn** [comment]
@UltraBlackLinux 
Thanks for working about it. But it didn't work :/.

But, I found something. The "queue option" is working! It opens my chat and writes /home. But its not sending it. (I know this is the feature of the option I chose. I just wanted to point out that not everything is bugged, I guess.)

And when I click the button in UI with the "Category" option filled with some text, game crashes.

Here is the config file.  (The "type" variable is "Category" because I was testing all options)

Have a nice day!

```
{
  "minemenuData": {
    "0": {
      "name": "/home",
      "icon": {
        "iconItem": "player_head",
        "enchanted": false,
        "skullOwner": "home"
      },
      "type": "category",
      "data": {
        "link": "/home",
        "1": {
          "name": "",
          "icon": {
            "iconItem": "",
            "enchanted": false,
            "skullOwner": ""
          },
          "type": "empty",
          "data": {}
        },
        "2": {
          "name": "",
          "icon": {
            "iconItem": "",
            "enchanted": false,
            "skullOwner": ""
          },
          "type": "empty",
          "data": {}
        },
        "3": {
          "name": "",
          "icon": {
            "iconItem": "",
            "enchanted": false,
            "skullOwner": ""
          },
          "type": "empty",
          "data": {}
        },
        "4": {
          "name": "",
          "icon": {
            "iconItem": "",
            "enchanted": false,
            "skullOwner": ""
          },
          "type": "empty",
          "data": {}
        }
      }
    },
    "1": {
      "name": "",
      "icon": {
        "iconItem": "",
        "enchanted": false,
        "skullOwner": ""
      },
      "type": "empty",
      "data": {}
    },
    "2": {
      "name": "",
      "icon": {
        "iconItem": "",
        "enchanted": false,
        "skullOwner": ""
      },
      "type": "empty",
      "data": {}
    },
    "3": {
      "name": "",
      "icon": {
        "iconItem": "",
        "enchanted": false,
        "skullOwner": ""
      },
      "type": "empty",
      "data": {}
    },
    "4": {
      "name": "",
      "icon": {
        "iconItem": "",
        "enchanted": false,
        "skullOwner": ""
      },
      "type": "empty",
      "data": {}
    }
  },
  "menuEntries": 5,
  "outerRadius": 75,
  "innerRadius": 25,
  "primaryColor": "#A00000CC",
  "secondaryColor": "#212121D0",
  "emptyItemIcon": "minecraft:air",
  "resetHeadCache": false,
  "resetConfig": false
}
```

Crash file when "Category" option selected:

[crash-2021-05-11_21.24.25-client.txt](https://github.com/UltraBlackLinux/MineMenuFabric/files/6461246/crash-2021-05-11_21.24.25-client.txt)

**Comment by UltraBlackLinux** [comment]
Please try the latest version with a reset config

**Comment by UltraBlackLinux** [comment]
closed due to inactivity
