### ISSUE TITLE
bug - Categories crash upon click

### ISSUE THREAD

**Issue by triphora** [UltraBlackLinux/MineMenuFabric#12]
![Crash report](https://gist.githubusercontent.com/natanfudge/3e543856d886a987ec66b7e8e4c680d8/raw/c73cce277973301d57b572a8fe6f116b4a581b51/crash.txt)

To reproduce - make a category, click on it

**Comment by UltraBlackLinux** [comment]
I think your config is messed up somehow - you should reset it - sorry xD

**Comment by UltraBlackLinux** [comment]
wot I can reproduce it

**Comment by UltraBlackLinux** [comment]
fixed it now
