### ISSUE TITLE
bug - All symbols should be converted to their unicode points

### ISSUE THREAD

**Issue by triphora** [UltraBlackLinux/MineMenuFabric#13]
I input the following as the message to be said:
`\*italics\* \*\*bold\*\* \*\*\*both\*\*\* \_underline_ \~strikethrough~`
And the config file registers it as the following:
`\\*italics\\* \\*\\*bold\\*\\* \\*\\*\\*both\\*\\*\\* \\_underline_ \\~strikethrough~`
That's all fine and dandy, I suppose, escaping the backslashes, but when I close out of mine menu and reopen it, the "Configure Entry" screen looks like this: 
`\*italics\* \*\*bold\*\* \*\*\*b`
I suspect this is most likely due to the slashes.
So, there should be some processing there to convert the `\` to [`\u005C`](https://unicode.scarfboy.com/?s=005C), as well as other characters. I can confirm this works because an apostrophe I put somewhere got converted to [`\u0027`](https://unicode.scarfboy.com/?s=0027).

**Comment by UltraBlackLinux** [comment]
@wafflecoffee 
I actually didn't do the config system - Report that at shedaniel's cloth config I guess? 
Edit: Could maybe try to fix that though

**Comment by UltraBlackLinux** [comment]
Oh wait a minute, I think that text just doesn't fit the textbox - you can "scroll" in that thing with the arrow keys

**Comment by triphora** [comment]
No; when I execute the order it only says the part up to the `\*\*\*b`

**Comment by UltraBlackLinux** [comment]
You can download a fix here: https://github.com/UltraBlackLinux/MineMenuFabric/actions/runs/827104336
