### ISSUE TITLE
[FEATURE] Support for custom icons

### ISSUE THREAD

**Issue by SmallPepperZ** [UltraBlackLinux/MineMenuFabric#14]
**Is your feature request related to a problem? Please describe.**
There are only so many icons you can use, and it would be nice if you could add more with a resource pack

**Describe the solution you'd like**
The ability to add custom icons in a resource pack that can be used by MineMenu

**Describe alternatives you've considered**
Retexturing actual items that I don't use would work, but isn't ideal because those items would have incorrect textures if I ever do use them, and there is a limited number that I could use

**Comment by UltraBlackLinux** [comment]
I guess I can do that with custom model data

**Comment by UltraBlackLinux** [comment]
https://www.planetminecraft.com/forums/communities/texturing/new-1-14-custom-item-models-tuto-578834/
you can try it with this
