### ISSUE TITLE
[FEATURE] Implement key press functionality, Allow movement while menu is open, and beautify UI.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [UltraBlackLinux/MineMenuFabric#17]
**Is your feature request related to a problem? Please describe.**
Compared to the forge version of MineMenu, this version is missing a lot of the visual changes as well as some functionality. One of the biggest features that was the point of the wheel was an option to press a specified key when selecting a button in the wheel (even unbound keys) as to allow more hotkeys without taking up space on the keyboard when using many mods.

**Describe the solution you'd like**
Add an additional menu like the forge version to select a key from the available list.

**Describe alternatives you've considered**
The only alternative is to just use the forge version, however I chose to make the switch from forge to fabric recently mostly because of how many more interesting client side mods are available compared to forge.

**Additional context**
I have nothing much else to add.

**Comment by UltraBlackLinux** [comment]
I have already thought about this, and it seems pretty difficult, unless I can just use some nice screen feature again.
I will propably not do this, if I am going to have to do weird and annoying things.

**Comment by UltraBlackLinux** [comment]
I finally have time to work on this mod further; the keybind feature is pushed out, I hope it's ok like I did it - please check out the gh-actions artifacts

**Comment by SmallPepperZ** [comment]
The feature seems to work for keys like `w` and `shift`, but if I try adding things like `F3` or `e`, it doesn't trigger those keybinds. I'm also wondering if it is possible to trigger unbound keybinds from other mods (and the vanilla game), for actions that you don't want to give one of your limited physical keys but still want to use occasionally

**Comment by UltraBlackLinux** [comment]
> The feature seems to work for keys like `w` and `shift`, but if I try adding things like `F3` or `e`, it doesn't trigger those keybinds. I'm also wondering if it is possible to trigger unbound keybinds from other mods (and the vanilla game), for actions that you don't want to give one of your limited physical keys but still want to use occasionally

Yep, that's a bug, that I am currently trying to find a fix for - Any Screen opening keys just won't do anything for some reason.

Regarding unused keys: I currently have no Idea, how I would do that - Will take some further investigation.

**Comment by UltraBlackLinux** [comment]
So I have now, after a lot of headaches, finally revamped the keybind feature - I am not extremely happy with it, but it's a step into the right direction, and a better solution than just copy-pasting the whole keybind screen code...

Please check it out - I hope you like it!
(I also fixed the keybinds not working correctly issue)

**Comment by SmallPepperZ** [comment]
This version works great! It works with unbound keybinds, and it seems to be consistently working. The only improvement I would have for it would be a way to search through the keybind options instead of cycling through. Thanks for the work you're putting into this

**Comment by UltraBlackLinux** [comment]
@SmallPepperZ 
Yeah, I also thought about this, but it will take a complete rearrangement of the config screen - I don't know how I would add a good search functionality anyways.
Gonna add this to my todolist, but nothing more that I can do at the moment.

Thanks for your guys' opinions!
