### ISSUE TITLE
[FEATURE] 1.17 support?

### ISSUE THREAD

**Issue by rx-dev** [UltraBlackLinux/MineMenuFabric#18]
**Is your feature request related to a problem? Please describe.**
I'm unsure if this project has 1.17 support

**Describe the solution you'd like**
The curseforge (and modrinth?) page doesn't have a release as latest as the releases tab here. Also makes it unsure whether or not 1.17 version exists.

Thanks!

**Comment by UltraBlackLinux** [comment]
I don't really want to update to an incomplete version - 1.17 is nowhere to be finished, I am gonna wait it out.
Also a tool, that I am using called DCEVM doesn't work on Java 16 - It's a pain to use Java without it...
I promise you, that I am gonna work on the 1.17 update at some point, but not now, I am sorry.
