### ISSUE TITLE
[FEATURE] Allow categories to have custom keybinds

### ISSUE THREAD

**Issue by Redo11** [UltraBlackLinux/MineMenuFabric#19]
Making custom keybinds, to open the wheel on predefined category would allow user to make "multiple" wheels, that they can access using different wheels.
This would make it faster to get to the features you want, rather than selecting categories of categories etc.

**Comment by UltraBlackLinux** [comment]
I don't think I can do that right now; I will look into it though

**Comment by UltraBlackLinux** [comment]
Decided against it - too much of a hassle, too messy, just impractical overall
