### ISSUE TITLE
[BUG]Click on the placeholder occurred problem

### ISSUE THREAD

**Issue by Sanluli36li** [UltraBlackLinux/MineMenuFabric#22]
## Expected Behavior
Click on the placeholder occurred problem

## Actual Behavior
placeholder

## Steps to Reproduce the Problem

1. click placeholder

I think it should do nothing, instead of throwing an exception and outputting an error message

![QQ截图20210619192252](https://user-images.githubusercontent.com/5201743/122640852-2093e500-d134-11eb-966c-ef4f6c2d7852.png)

**Comment by UltraBlackLinux** [comment]
I fixed that in the hotfix today - It should actually open the config screen instead of doing nothing.
