### ISSUE TITLE
Skulls - are they working correctly?

### ISSUE THREAD

**Issue by danteali** [UltraBlackLinux/MineMenuFabric#23]
I assume the intended behaviour is to enter 'minecraft:skull' or 'skull' for the Icon, then the skullowner's playername (or mob name) should be entered under 'skullowner'? Whatever I try I can't get it to work. 

Not sure if this feature is fully complete yet as the 'Skullowner' label under Icons is only accessible by right clicking to go backwards through the Icon options. There is also a line in the json config file for skullowner.

I can't seem to make it work no matter what I try. In the GUI, the text box is always locked and nothing can be typed. If I manually try to edit the json, it doesn't seem to matter what I put in for skullowner.

And if it's not working yet, what is the purpose of the option to clear the skull cache?

Or maybe I'm just trying to use it incorrectly?

**Comment by UltraBlackLinux** [comment]
The skullowner is only accessible via "player_head" I should change this actually.
The backwards scrolling is not intended to circumvent that, you found a bug xD

**Comment by danteali** [comment]
Perfect. Thanks. 

I totally don't want to ask you to do any extra work as I appreciate that maintaining this is already time consuming but might be worth expanding the Curseforge/Modrinth description to explain how to use the mod a little. 

You'd probably avoid questions like this in future :)
I didn't realise that "player_head" was the icon which would enable skulls.

Really appreciate what you've done with this. I've just moved to a fabric server from Paper and this is one of the mods which I needed before I could make the move. I've got kids in the house who wouldn't be able to use commands properly so needed something which they could easily use as a shortcut to various commands (teleporting mainly).

P.S. Is there any way to string multiple commands together in one button (not a problem if the answer is no)?
e.g. /gamemode creative; /tp @p 100 64 100

**Comment by UltraBlackLinux** [comment]
> I didn't realise that "player_head" was the icon which would enable skulls.

Yeah, it is a bit hard to find, I will add a tip for it. - Also everything other than player_head doesn't load custom skins sadly.

> P.S. Is there any way to string multiple commands together in one button (not a problem if the answer is no)?
> e.g. /gamemode creative; /tp @p 100 64 100

I will try my best to implement that - Might need a new category, as I don't want people to type the corresponding symbol and then wonder, why their message is being split.

**Comment by UltraBlackLinux** [comment]
Okay done - what do you think?

https://github.com/UltraBlackLinux/MineMenuFabric/actions/runs/957825869 - 1.16
https://github.com/UltraBlackLinux/MineMenuFabric/actions/runs/957818014 - 1.17

**Comment by danteali** [comment]
Brilliant!
That's awesome. Many thanks.

Probably worth a quick explanation in the mod description or you'' get the inevitable questions about what 'Say Multiple' means, or asking what character is used as the separator.

Thanks again. I'll close the issue.
