### ISSUE TITLE
1.15.2 not working[BUG]

### ISSUE THREAD

**Issue by Varrial** [UltraBlackLinux/MineMenuFabric#24]
## Expected Behavior
well... it should work 

## Actual Behavior
![image](https://user-images.githubusercontent.com/73936910/134082762-d138497c-249c-44e9-8235-5e73b6dca709.png)

## Steps to Reproduce the Problem

1. Install MineMenuFabric form CurseForge
2. Run a game

On 6.0 and 5.0 I try change requariments in fabric.mod.json but then game crashes. Also I have tried lover mod version but then required other version of ModMenu. When I this time changing requariments game don't crash but MineMenuFabric dosn't work at all.

**Comment by UltraBlackLinux** [comment]
_Read Please_
What does it say? >It requires cloth config<

**Comment by Varrial** [comment]
cloth config 4.10.6 dosn't exist for 1.15.2

**Comment by UltraBlackLinux** [comment]
I could lower the version requirement then - What's the newest version available for 1.15?

**Comment by Varrial** [comment]
![image](https://user-images.githubusercontent.com/73936910/135468034-9efc75cc-cab5-486f-8a9b-85d5d32b4b56.png)

**Comment by Varrial** [comment]
But, as I previoulsy wrote i change requirement in fabric.mod.json but game crashed.
