### ISSUE TITLE
Having the number value of entries to 7 breaks the circle[BUG]

### ISSUE THREAD

**Issue by Herobrine2143** [UltraBlackLinux/MineMenuFabric#25]
## Expected Behavior
It should complete the circle in every entry.

## Actual Behavior
The circle breaks not being able to complete.

## Steps to Reproduce the Problem
Set the number entries to 7
![image](https://user-images.githubusercontent.com/22053132/134669130-5f508f11-23d5-43dc-9bea-cf8cb29a8b88.png)

**Comment by UltraBlackLinux** [comment]
I have no clue at all - Mind just not using 7 circle entries? XD

**Comment by Herobrine2143** [comment]
Welp, sure.
