### ISSUE TITLE
bug - Client desync as a result of clicking an option in the menu

### ISSUE THREAD

**Issue by triphora** [UltraBlackLinux/MineMenuFabric#9]
https://qu.ax/Op7.mkv
Keep an eye on the fourth hotbar slot. Client thinks it should interact with the environment when clicking an option in MineMenu, but server apparently does not receive it. Probably should prevent it from clicking anywhere outside of the menu anyway. Bit complicated to explain, but I think the video linked demonstrates it relatively well. Uses a flower pot to show it in action.

Thanks for making this port :) Works very well, this is the only bug I've come across so far! :smiley:

**Comment by UltraBlackLinux** [comment]
@wafflecoffee 
Hmm, unsure, this might be some mod messing with screens, as they don't pass input through to the outside - as far as I know

**Comment by triphora** [comment]
Actually. If that's the case, I know exactly which mod is causing it. Will need a bit to test
